# vars/cluster_config.yml

# --- Global Settings ---
kube_user: "{{ ansible_user | default('ubuntu') }}"

# --- Offline Installation Settings ---
offline_install: false
offline_pkg_type: "zip"               # Options: "zip" or "dir"
offline_pkg_source: "controller"      # Options: "controller" (transfer from host) or "remote" (already on server)
offline_pkg_path: "k8s_rpm.zip"       # Local path (if source=controller) or Remote path (if source=remote)
remote_pkg_dir: "/tmp/k8s_packages"  # Directory on remote node to store/extract packages
ignore_preflight_errors: ""  # Errors to ignore during kubeadm init/join

# --- Installation Settings (create_k8s.yml) ---
runtime: crio  # Options: crio, containerd
kube_version: "1.28"
crio_version: "v1.28"
cni_plugins_version: "v1.6.2"
cni_plugins_url: "https://github.com/containernetworking/plugins/releases/download/{{ cni_plugins_version }}/cni-plugins-linux-amd64-{{ cni_plugins_version }}.tgz"

# --- Networking Settings ---
cni_plugin: flannel  # Options: calico, flannel
calico_version: v3.26.0
flannel_version: v0.26.0

# --- Firewall Settings ---
firewall_enabled: true
firewall_allowed_ports_common:
  - { port: "6443", proto: "tcp" }         # Kubernetes API server
  - { port: "2379-2380", proto: "tcp" }    # etcd server client API
  - { port: "10250", proto: "tcp" }        # Kubelet API
  - { port: "10251", proto: "tcp" }        # kube-scheduler
  - { port: "10252", proto: "tcp" }        # kube-controller-manager
  - { port: "30000-32767", proto: "tcp" }  # NodePort Services

firewall_allowed_ports_cni:
  calico:
    - { port: "179", proto: "tcp" }        # Calico BGP
    - { port: "4789", proto: "udp" }       # Calico VXLAN
  flannel:
    - { port: "8472", proto: "udp" }       # Flannel VXLAN

# These are internal mappings for CNI manifests and CIDRs
# You can modify them if you need custom manifests or CIDRs
cni_manifest_urls:
  calico: "https://raw.githubusercontent.com/projectcalico/calico/{{ calico_version }}/manifests/calico.yaml"
  flannel: "https://github.com/flannel-io/flannel/releases/download/{{ flannel_version }}/kube-flannel.yml"

cni_default_cidrs:
  calico: "192.168.0.0/16"
  flannel: "10.244.0.0/16"

# If pod_network_cidr is not specified, it will use the default from above
pod_network_cidr: "{{ cni_default_cidrs[cni_plugin] }}"

# --- High Availability Settings ---
control_plane_endpoint: "{{ hostvars[groups['controlplane'][0]].ansible_host }}" # Auto-set to first master, override for LB
kubeconfig_on_all_cp: false

# --- Reset Settings (reset-k8s-cluster.yml) ---
remove_packages: false

# --- Upgrade Settings (upgrade_k8s.yml) ---
target_version: "1.30" # Should typically be passed via -e at runtime
